definitions:
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Gianfranco Capodici
    url: http://www.swagger.io/support
  description: This is a simple API development by Gianfranco Capodici.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: Arquitectura del bootcamp - API
  version: "1.0"
paths:
  /users:
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: List users
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not found users
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/web.Response'
swagger: "2.0"
